GET http://localhost:3000/Flights HTTP/1.1

################################

GET http://localhost:3000/Role HTTP/1.1

################################

GET http://localhost:3000/User HTTP/1.1

################################

GET http://localhost:3000/Booking HTTP/1.1
 





